name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Build and push Docker image
        run: |
          docker login ${{ secrets.REGISTRY_NAME }}.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }}
          docker build -t ${{ secrets.IMAGE_NAME }} --build-arg="ACCESS_KEY=${{secrets.ACCESS_KEY}}" .
          docker tag ${{ secrets.IMAGE_NAME }} ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest
          docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest
        env:
          DOCKER_BUILDKIT: 1
        working-directory: .

      - name: Logout from Azure
        run: |
          az logout

### List of Secrets
## APP
#-IMAGE_NAME - Docker image name.
#-ACCESS_KEY - Repo Access Key with full Repo scope perms.

## AZURE
#-AZURE_CLIENT_ID
#-AZURE_CLIENT_SECRET
#-AZURE_SUBSCRIPTION_ID
#-AZURE_TENANT_ID
#-REGISTRY_NAME